import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "@mui/material/Button";
import CartMenu from "./../components/cartmenu/CartMenu";
import { useState } from "react";

const Home: NextPage = () => {
  const [isOpen, setIsOpen] = useState<boolean>(false);

  const toggleDrawer =
  (open: boolean) =>
  (event: React.KeyboardEvent | React.MouseEvent) => {
    if (
      event &&
      event.type === "keydown" &&
      ((event as React.KeyboardEvent).key === "Tab" ||
        (event as React.KeyboardEvent).key === "Shift")
    ) {
      return;
    }

    setIsOpen(open);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button onClick={() => setIsOpen(!isOpen)}>{"right"}</Button>
        <CartMenu isOpen={isOpen} toggleDrawer={toggleDrawer} />
      </main>
    <div>
      <MainSlider/>
    </div>
  );
};

export default Home;
